### ISSUE TITLE
Can't handle mentions

### ISSUE THREAD

**Issue by sudo-do** [nerdguyahmad/discord-chatbot#1]
https://pasteboard.co/JZGSTwH.jpg

**Comment by sudo-do** [comment]
at least it should ignore them

**Comment by nerdguyahmad** [comment]
Can you elaborate? The screenshot you are showing doesn't has any bot in it, (Are you using ordinary user?)

**Comment by nerdguyahmad** [comment]
There's no bot in that screenshot, (If you are using an ordinary user, Please don't. you can get your account banned). For mention, From that screenshot, I'm guessing you are talking of bot using user ID. It is because it uses prsaw library to get random responses from the message so I can't do anything about it.

Can you elaborate what do you mean by "ignoring" them?

**Comment by sudo-do** [comment]
`message.content = re.sub('<@.*?>', '', message)`

**Comment by nerdguyahmad** [comment]
@sudo-do 
https://github.com/nerdguyahmad/discord-chatbot/pull/4

**Comment by nerdguyahmad** [comment]
It is fixed in #4 PR.
